In [1]:
# Main NMF equation: v = w*h --> (r*c) = (r*t)*(t*c)

import numpy as np
import tqdm


In [ ]:
def kl(v, w, h):
    #find KL routines 

In [14]:
random_init = True

#global parameters
numtopics = 10
iter_tol = 10e-4 #Tolerance for converging iterations

#Params for random initialization

if random_init:
    numrows = 12
    numcols = 20
    low_init = 0
    high_init = 10
    w = np.random.randint(low_init, high_init, numrows*numtopics).reshape(numrows, numtopics)
    h = np.random.randint(low_init, high_init, numtopics*numcols).reshape(numtopics,numcols)
    
else:
    pass
    #write corpus parser here

v = np.dot(w, h)
print('w:')
print(w)
print('h:')
print(h)

w:
[[0 8 1 1 1 5 9 5 3 9]
 [9 1 1 2 0 7 5 8 5 3]
 [0 7 8 0 3 9 4 5 1 5]
 [3 6 4 1 5 5 0 8 5 7]
 [3 9 7 4 8 1 0 8 6 9]
 [7 7 8 6 2 7 7 4 8 6]
 [6 6 2 0 4 6 4 0 5 2]
 [3 4 5 7 3 5 1 0 0 6]
 [3 5 5 4 9 4 6 5 4 3]
 [6 1 0 6 9 1 5 3 1 3]
 [9 1 4 7 5 4 7 4 4 6]
 [8 0 2 7 0 9 8 4 0 3]]
h:
[[3 7 7 9 5 2 7 5 7 1 4 7 5 3 5 7 1 6 4 5]
 [3 7 4 3 7 7 2 9 8 3 0 2 0 4 8 9 7 7 5 0]
 [0 1 6 9 6 4 9 1 7 8 4 2 2 0 1 8 6 1 1 9]
 [1 0 8 4 6 7 6 2 2 9 1 6 3 8 6 7 8 7 6 0]
 [0 5 2 4 2 8 0 9 3 3 1 6 9 5 0 9 9 5 7 6]
 [7 2 5 6 7 0 7 3 4 8 7 0 4 6 8 9 6 1 1 2]
 [0 2 3 1 2 5 8 9 7 1 1 8 7 7 4 2 6 6 8 0]
 [3 9 3 2 9 8 7 5 0 9 2 0 9 3 9 4 2 8 2 7]
 [4 5 9 7 3 3 0 2 3 5 7 0 3 5 5 7 3 5 6 4]
 [6 6 8 4 2 2 4 5 6 6 7 4 8 8 4 4 2 7 1 6]]


In [ ]:

while kl(v, w, h) > iter_tol: